#include "UI/ProvelScreens.hpp"

#include "UI/DisplaySize.hpp"

#define DEBUG 2
#include "Debug.hpp"

namespace Provel {

#define PROVEL_SCREENS_LINE_NUM (8)
#define PROVEL_SCREENS_LINE_WIDTH (DISPLAY_X)
#define PROVEL_SCREENS_LINE_HEIGHT (DISPLAY_Y / PROVEL_SCREENS_LINE_NUM)
#define PROVEL_SCREENS_LINE_ROW(num) (num * PROVEL_SCREENS_LINE_WIDTH)
#define PROVEL_SCREENS_LINE_COL(num) (num * PROVEL_SCREENS_LINE_HEIGHT)

ScreenSplash::ScreenSplash()
{
	dbg("\r\n");
	timeout = 1000;
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: PROVEL");
	version = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "text: " VERSION_TEXT);

	Add(title);
	Add(version);
}

ScreenSplash::~ScreenSplash()
{
}


ScreenHoming::ScreenHoming()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: HOMING");
	stop = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: STOP", 0, 0);
	status = new Status(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT);

	Add(title);
	Add(stop);
	Add(status);
}

ScreenHoming::~ScreenHoming()
{
}


ScreenFileLoaded::ScreenFileLoaded()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: FILE LOADED");
	startOrClear = new ButtonDouble(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: START", "btn: CLEAR");

	Add(title);
	Add(startOrClear);
}

ScreenFileLoaded::~ScreenFileLoaded()
{
}

ScreenFault::ScreenFault()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: FAULT");
	clear = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: CLEAR", 0, 0);
	status = new Status(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT);

	Add(title);
	Add(clear);
	Add(status);
}

ScreenFault::~ScreenFault()
{
}

ScreenHeating::ScreenHeating()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: HEATING");
	text = new Text(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "text: TEXT");
	stop = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: STOP", 0, 0);
	status = new Status(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT);

	Add(title);
	Add(text);
	Add(stop);
	Add(status);
}

ScreenHeating::~ScreenHeating()
{
}

ScreenIdle::ScreenIdle()
{
	Title *title;
	Button *load;
	Button *home;
	Button *printer;
	Button *purge;

	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: IDLE");
	load = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: LOAD", 0, 0);
	home = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: HOME", 0, 0);
	printer = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: PRINTER", 0, 0);
	purge = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: PURGE", 0, 0);

	Add(title);
	Add(load);
	Add(home);
	Add(printer);
	Add(purge);
}

ScreenIdle::~ScreenIdle()
{
}

ScreenLoading::ScreenLoading()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: LOADING FILE");
	cancel = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: CANCEL", 0, 0);

	Add(title);
	Add(cancel);
}

ScreenLoading::~ScreenLoading()
{
}


ScreenPrinter::ScreenPrinter()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: PRINTER");
	plusMinus = new ButtonDouble(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: PLUS", "btn: MINUS");
	zCalibrate = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: ZCALIBRATE", 0, 0);
	indexCup = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: INDEXCUP", 0, 0);
	access = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: ACCESS", 0, 0);
	enterExit = new ButtonDouble(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: ENTER", "btn: EXIT");

	Add(title);
	Add(plusMinus);
	Add(zCalibrate);
	Add(indexCup);
	Add(access);
	Add(enterExit);
}

ScreenPrinter::~ScreenPrinter()
{
}

ScreenPrinting::ScreenPrinting()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: PRINTING");
	text = new Text(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "text: TEXT");
	status = new Status(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT);

	Add(title);
	Add(text);
	Add(status);
}

ScreenPrinting::~ScreenPrinting()
{
}

ScreenPurging::ScreenPurging()
{
	Title *title;
	Text *text;
	Button *stop;
	Status *status;

	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: PURGING");
	text = new Text(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "text: TEXT");
	stop = new Button(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: STOP", 0, 0);
	status = new Status(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT);

	Add(title);
	Add(text);
	Add(stop);
	Add(status);
}

ScreenPurging::~ScreenPurging()
{
}

ScreenWarning::ScreenWarning()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: WARNING");
	text = new Text(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "text: TEXT");

	Add(title);
	Add(text);
}

ScreenWarning::~ScreenWarning()
{
}

ScreenZCalibrate::ScreenZCalibrate()
{
	title = new Title(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "title: ZCALIBRATE");
	offset = new Text(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "text: OFFSET");
	plusMinus = new ButtonDouble(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: PLUS", "btn: MINUS");
	enterExit = new ButtonDouble(PROVEL_SCREENS_LINE_ROW(0), PROVEL_SCREENS_LINE_COL(0), PROVEL_SCREENS_LINE_WIDTH, PROVEL_SCREENS_LINE_HEIGHT, "btn: ENTER", "btn: EXIT");

	Add(title);
	Add(offset);
	Add(plusMinus);
	Add(enterExit);
}

ScreenZCalibrate::~ScreenZCalibrate()
{
}

}
